---
apiVersion: v1
kind: Template
metadata:
  name: policy-template
objects:
- apiVersion: authentication.istio.io/v1alpha1
  kind: Policy
  metadata:
    name: "${DEPLOYMENT}-mtls-policy"
  spec:
    peers:
    - mtls:
        mode: STRICT
    targets:
    - name: "${DEPLOYMENT}"
parameters:
- description: Deployment name
  name: DEPLOYMENT
