---
apiVersion: v1
kind: Template
metadata:
  name: policy-template
objects:
- apiVersion: networking.istio.io/v1alpha3
  kind: VirtualService
  metadata:
    name: productpage-virtualservice
  spec:
    hosts: 
    - "productpage-bookretail-istio-system.${BASE_URL}"
    gateways:
    - bookretail-wildcard-gateway.bookretail-istio-system.svc.cluster.local
    http:
    - match:
      - uri:
          prefix: /
      route:
      - destination:
          port:
            number: 9080
          host: productpage.bookinfo.svc.cluster.local
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    annotations:
      openshift.io/host.generated: true
    labels:
      app: productpage
    name: productpage-gateway
  spec:
    host: "productpage-bookretail-istio-system.${BASE_URL}"
    port:
      targetPort: https
    tls:
      termination: passthrough
    to:
      kind: Service
      name: istio-ingressgateway
      weight: 100
    wildcardPolicy: None
- apiVersion: networking.istio.io/v1alpha3
  kind: Gateway
  metadata:
    name: bookretail-wildcard-gateway
  spec:
    selector:
      istio: ingressgateway
    servers:
    - port:
        number: 443
        name: https
        protocol: HTTPS
      tls:
        mode: SIMPLE
        privateKey: /etc/istio/ingressgateway-certs/tls.key
        serverCertificate: /etc/istio/ingressgateway-certs/tls.crt
      hosts:
      - "*.${BASE_URL}"
parameters:
- description: Base url
  name: BASE_URL
