---
apiVersion: v1
kind: Template
metadata:
  name: destination-rule-template
objects:
- apiVersion: networking.istio.io/v1alpha3
  kind: DestinationRule
  metadata:
    name: ${SERVICE_NAME}-mtls-destinationrule
  spec:
    host: ${SERVICE_NAME}.bookinfo.svc.cluster.local
    trafficPolicy:
      tls:
        mode: ISTIO_MUTUAL
parameters:
- description: Service name
  name: SERVICE_NAME
